version: '2.3'

services:

  redis:
    image: redis:4.0
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - ./data.tmp:/data

  redis-commander: # => http://localhost:1102/
    image: rediscommander/redis-commander
    hostname: redis-commander
    ports:
      - 1102:8081
    environment:
      REDIS_HOSTS: db00:172.17.0.1:6379:0,db01:172.17.0.1:6379:1,db02:172.17.0.1:6379:2,db03:172.17.0.1:6379:3,db10:172.17.0.1:6379:10,db11:172.17.0.1:6379:11,db12:172.17.0.1:6379:12,db13:172.17.0.1:6379:13
